server:
  port: 8081
logging:
  level:
    org.exampledriven: DEBUG
---
spring:
    profiles: heroku
    mvc:
      async:
        request-timeout: 3600000
    rabbitmq:
      addresses: amqp://uyjgxslh:06EXxqvYf5bnI2P6o6143NBeGTMYFqyY@puma.rmq.cloudamqp.com/uyjgxslh
server:
  port: ${PORT}
